name: Build and Push API (.NET) Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "api/src/**"
      - "api/Fishio.sln"
      - "api/Dockerfile"
      - ".github/workflows/docker-build-push-api.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "api/src/**"
      - "api/Fishio.sln"
      - "api/Dockerfile"
      - ".github/workflows/docker-build-push-api.yaml"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-api
  # DOCKERFILE_PATH i BUILD_CONTEXT są używane bezpośrednio w kroku build-push-action

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current date and Git info
        id: build_info
        run: |
          echo "BUILD_TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          GIT_TAG=$(git describe --tags --abbrev=0 --exact-match 2>/dev/null || echo "")
          if [ -n "$GIT_TAG" ]; then
            echo "APP_VERSION_TAG=$GIT_TAG" >> $GITHUB_OUTPUT
          else
            echo "APP_VERSION_TAG=none" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=${{ steps.build_info.outputs.APP_VERSION_TAG }},enable=${{ steps.build_info.outputs.APP_VERSION_TAG != 'none' }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image for API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_INFO_GIT_SHA=${{ steps.build_info.outputs.GIT_SHA }}
            BUILD_INFO_TIMESTAMP=${{ steps.build_info.outputs.BUILD_TIMESTAMP }}
            BUILD_INFO_VERSION_TAG=${{ steps.build_info.outputs.APP_VERSION_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
