/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { BuildInformation } from './buildInformation';

export interface ApplicationInfoDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  version?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  features?: string[] | null;
  buildInfo?: BuildInformation;
}
