/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type CategoryCalculationLogic = (typeof CategoryCalculationLogic)[keyof typeof CategoryCalculationLogic];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryCalculationLogic = {
  ManualAssignment: 'ManualAssignment',
  MaxValue: 'MaxValue',
  SumValue: 'SumValue',
  MinValue: 'MinValue',
  FirstOccurrence: 'FirstOccurrence',
  LastOccurrence: 'LastOccurrence'
} as const;
