/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type CategoryEntityType = (typeof CategoryEntityType)[keyof typeof CategoryEntityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryEntityType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3
} as const;
