/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type CategoryType = typeof CategoryType[keyof typeof CategoryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
