/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type CategoryMetric = (typeof CategoryMetric)[keyof typeof CategoryMetric];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryMetric = {
  NotApplicable: 'NotApplicable',
  LengthCm: 'LengthCm',
  WeightKg: 'WeightKg',
  FishCount: 'FishCount',
  SpeciesVariety: 'SpeciesVariety',
  TimeOfCatch: 'TimeOfCatch'
} as const;
