/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CategoryType } from './categoryType';
import type { CategoryMetric } from './categoryMetric';
import type { CategoryCalculationLogic } from './categoryCalculationLogic';
import type { CategoryEntityType } from './categoryEntityType';

export interface CategoryDefinitionDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  type?: CategoryType;
  metric?: CategoryMetric;
  calculationLogic?: CategoryCalculationLogic;
  entityType?: CategoryEntityType;
  requiresSpecificFishSpecies?: boolean;
  allowManualWinnerAssignment?: boolean;
}
