/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type CategoryCalculationLogic = typeof CategoryCalculationLogic[keyof typeof CategoryCalculationLogic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryCalculationLogic = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;
