/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CompetitionCategoryDto } from './competitionCategoryDto';
import type { CompetitionParticipantDto } from './competitionParticipantDto';
import type { CompetitionStatus } from './competitionStatus';
import type { CompetitionType } from './competitionType';

export interface CompetitionDetailsDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  startTime?: string;
  endTime?: string;
  status?: CompetitionStatus;
  type?: CompetitionType;
  /** @nullable */
  fisheryName?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  participantsCount?: number;
  /** @nullable */
  primaryScoringInfo?: string | null;
  /** @nullable */
  organizerName?: string | null;
  organizerId?: number;
  /** @nullable */
  rules?: string | null;
  /** @nullable */
  resultsToken?: string | null;
  /** @nullable */
  fisheryLocation?: string | null;
  /** @nullable */
  categories?: CompetitionCategoryDto[] | null;
  /** @nullable */
  participantsList?: CompetitionParticipantDto[] | null;
}
