/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type CompetitionType = (typeof CompetitionType)[keyof typeof CompetitionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompetitionType = {
  Public: 'Public',
  Private: 'Private'
} as const;
