/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CompetitionSummaryDto } from './competitionSummaryDto';

export interface CompetitionSummaryDtoPaginatedList {
  /** @nullable */
  items?: CompetitionSummaryDto[] | null;
  pageNumber?: number;
  readonly totalPages?: number;
  readonly totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
