/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CompetitionStatus } from './competitionStatus';
import type { CompetitionType } from './competitionType';

export interface CompetitionSummaryDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  startTime?: string;
  endTime?: string;
  status?: CompetitionStatus;
  type?: CompetitionType;
  /** @nullable */
  fisheryName?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  participantsCount?: number;
  /** @nullable */
  primaryScoringInfo?: string | null;
}
