/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface CreateCompetitionCommand {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  startDate?: string;
  endDate?: string;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  fishSpeciesIds?: number[] | null;
  /** @nullable */
  judgeIds?: string[] | null;
}
