/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CompetitionStatus } from './competitionStatus';

export interface DashboardCompetitionSummaryDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  startTime?: string;
  status?: CompetitionStatus;
  /** @nullable */
  fisheryName?: string | null;
  isOrganizer?: boolean;
  isJudge?: boolean;
  isParticipant?: boolean;
}
