/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { DashboardCompetitionSummaryDto } from './dashboardCompetitionSummaryDto';
import type { DashboardFisherySummaryDto } from './dashboardFisherySummaryDto';
import type { DashboardLogbookSummaryDto } from './dashboardLogbookSummaryDto';

export interface DashboardDto {
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  myUpcomingCompetitions?: DashboardCompetitionSummaryDto[] | null;
  /** @nullable */
  myRecentCompetitions?: DashboardCompetitionSummaryDto[] | null;
  /** @nullable */
  recentLogbookEntries?: DashboardLogbookSummaryDto[] | null;
  /** @nullable */
  openCompetitions?: DashboardCompetitionSummaryDto[] | null;
  /** @nullable */
  featuredFisheries?: DashboardFisherySummaryDto[] | null;
}
