/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface DashboardFisherySummaryDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  fishSpeciesCount?: number;
}
