/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { FishSpeciesSimpleDto } from './fishSpeciesSimpleDto';

export interface FisheryDto {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  userId?: number | null;
  /** @nullable */
  userName?: string | null;
  created?: string;
  /** @nullable */
  fishSpecies?: FishSpeciesSimpleDto[] | null;
}
