/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface FishSpeciesDto {
  id?: number;
  /** @nullable */
  name?: string | null;
}
