/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CategoryType } from './categoryType';

export type GetGlobalCategoryDefinitionsParams = {
  FilterByType?: CategoryType;
};
