/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { MyCompetitionFilter } from './myCompetitionFilter';

export type GetUserCompetitionsListParams = {
  PageNumber: number;
  PageSize: number;
  Filter: MyCompetitionFilter;
  SearchTerm?: string;
};
