/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CompetitionStatus } from './competitionStatus';
import type { CompetitionType } from './competitionType';

export type ListAvailableCompetitionsParams = {
  SearchTerm?: string;
  Status?: CompetitionStatus;
  Type?: CompetitionType;
  FromDate?: string;
  ToDate?: string;
  Page: number;
  PageSize: number;
};
