/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type ParticipantRole = (typeof ParticipantRole)[keyof typeof ParticipantRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipantRole = {
  Organizer: 'Organizer',
  Judge: 'Judge',
  Competitor: 'Competitor',
  Guest: 'Guest'
} as const;
