/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export type ParticipantRole = (typeof ParticipantRole)[keyof typeof ParticipantRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipantRole = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3
} as const;
