/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface RecordFishCatchCommand {
  competitionId?: number;
  /** @nullable */
  participantId?: string | null;
  fishSpeciesId?: number;
  length?: number;
  /** @nullable */
  weight?: number | null;
  /** @nullable */
  notes?: string | null;
}
