/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface RecordCompetitionFishCatchCommand {
  competitionId?: number;
  participantEntryId?: number;
  fishSpeciesId?: number;
  /** @nullable */
  image?: Blob | null;
  catchTime?: string;
  /** @nullable */
  lengthInCm?: number | null;
  /** @nullable */
  weightInKg?: number | null;
}
