/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface SpecialCategoryDefinitionCommandDto {
  categoryDefinitionId?: number;
  /** @nullable */
  fishSpeciesId?: number | null;
  /** @nullable */
  customNameOverride?: string | null;
}
