/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { CompetitionType } from './competitionType';

export interface UpdateCompetitionCommand {
  id?: number;
  /** @nullable */
  name?: string | null;
  startTime?: string;
  endTime?: string;
  fisheryId?: number;
  /** @nullable */
  rules?: string | null;
  type?: CompetitionType;
  /** @nullable */
  image?: Blob | null;
  removeCurrentImage?: boolean;
}
