/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */

export interface UserLogbookEntryDto {
  id?: number;
  /** @nullable */
  imageUrl?: string | null;
  catchTime?: string;
  /** @nullable */
  lengthInCm?: number | null;
  /** @nullable */
  weightInKg?: number | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  fishSpeciesId?: number | null;
  /** @nullable */
  fishSpeciesName?: string | null;
  /** @nullable */
  fisheryId?: number | null;
  /** @nullable */
  fisheryName?: string | null;
  created?: string;
}
