/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Fishio API
 * OpenAPI spec version: v1
 */
import type { UserLogbookEntryDto } from './userLogbookEntryDto';

export interface UserLogbookEntryDtoPaginatedList {
  /** @nullable */
  items?: UserLogbookEntryDto[] | null;
  pageNumber?: number;
  readonly totalPages?: number;
  readonly totalCount?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
}
